# Generated by Django 5.2.3 on 2025-07-04 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255)),
                ('created_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1877)])),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_album', models.CharField(max_length=255)),
                ('created_at', models.DateField()),
                ('musician', models.ManyToManyField(to='shop.musician')),
            ],
        ),
    ]
